services:
  - name: my-flask-app
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: your-database-url
      - key: FLASK_ENV
        value: production